[package]
name = "chartsy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version="0.12.1", default-features=false, features=["canvas", "advanced", "svg", "image"]}
iced_runtime = { version="0.12.1", default-features=false }
iced_style = { version="0.12.1", default-features=false }
rand = "0.8.5"
mongodb = {version="2.8.0", features=["async-std-runtime"], default-features=false}
dropbox-sdk = { version="0.18.0", features=["dbx_files", "dbx_users", "default_client"] }
svg = "0.16.0"
image = "0.24.8"
pwhash = "1.0.0"
directories = "5.0.1"
async-recursion = "1.0.5"
lettre = { version="0.11.4", default-features=false, features = ["smtp-transport", "hostname", "builder", "async-std1-rustls-tls"] }
regex = "1.10.3"