[package]
name = "chartsy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version="0.10.0", features=["canvas", "advanced"]}
iced_runtime = "0.1.1"
iced_style = "0.9.0"
rand = "0.8.5"
mongodb = {version="2.6.1", features=["async-std-runtime"], default-features=false}
svg = "0.13.1"
iced_aw = {version= "0.7.0", features=["modal", "card", "tabs", "tab_bar"]}
